name: Lighthouse Audit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@v0.3.2
